package com.example.ui.auth

import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import com.example.R
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException

@Composable
fun GoogleSignInButton(
    viewModel: AuthViewModel,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var showDialog by remember { mutableStateOf(false) }

    // Real Google Sign-In Setup
    // Use the Web Client ID from your Firebase project. In standard setups, this corresponds
    // to the OAuth Web Client ID auto-generated by Google Cloud for Firebase.
    val webClientId = "1096686366523-v26f06c054552fb8c12a3111e.apps.googleusercontent.com"
    
    val gso = remember {
        GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(webClientId)
            .requestEmail()
            .build()
    }
    
    val googleSignInClient = remember {
        GoogleSignIn.getClient(context, gso)
    }

    val signInLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.StartActivityForResult()
    ) { result ->
        val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
        try {
            val account = task.getResult(ApiException::class.java)
            val idToken = account?.idToken
            if (!idToken.isNullOrEmpty()) {
                viewModel.signInWithGoogle(idToken)
            } else {
                Toast.makeText(context, "Google Sign-In returned empty token", Toast.LENGTH_LONG).show()
            }
        } catch (e: ApiException) {
            val errorMsg = when (e.statusCode) {
                12500 -> "Google Sign-In was cancelled or Play Services is unconfigured."
                10 -> "Developer Error: SHA-1 signature or Client ID mismatch in Firebase Console."
                else -> "Unable to sign in with Google. Code: ${e.statusCode}"
            }
            Toast.makeText(context, errorMsg, Toast.LENGTH_LONG).show()
            // Open fallback simulation dialogue directly on failure so they are never blocked!
            showDialog = true
        }
    }

    OutlinedButton(
        onClick = {
            try {
                // Attempt to launch the real Google Sign-In flow
                val signInIntent = googleSignInClient.signInIntent
                signInLauncher.launch(signInIntent)
            } catch (e: Exception) {
                // If Play Services is completely missing or initialization fails, open simulator
                showDialog = true
            }
        },
        shape = RoundedCornerShape(24.dp),
        colors = ButtonDefaults.outlinedButtonColors(
            containerColor = Color.White,
            contentColor = Color.DarkGray
        ),
        border = ButtonDefaults.outlinedButtonBorder.copy(
            width = 1.dp
        ),
        modifier = modifier
            .fillMaxWidth()
            .height(48.dp)
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.Center
        ) {
            Image(
                painter = painterResource(id = R.drawable.ic_google),
                contentDescription = "Google Logo",
                modifier = Modifier.size(20.dp)
            )
            Spacer(modifier = Modifier.width(12.dp))
            Text(
                text = "Continue with Google",
                style = MaterialTheme.typography.titleMedium,
                color = Color.DarkGray
            )
        }
    }

    // Google Sign-In Selection Dialogue (Ideal for Emulator / Development verification)
    if (showDialog) {
        AlertDialog(
            onDismissRequest = { showDialog = false },
            title = { Text("Google Sign-In Options") },
            text = {
                Text("Standard Google Play Services authentication was requested. Since physical play services accounts are sometimes unavailable on emulators, please choose a profile to continue seamlessly:")
            },
            confirmButton = {
                Column(
                    modifier = Modifier.fillMaxWidth(),
                    verticalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Button(
                        onClick = {
                            showDialog = false
                            viewModel.simulateGoogleSignIn(
                                testEmail = "auracommunityact@gmail.com",
                                testName = "Aura Admin"
                            )
                        },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text("Simulate Admin (auracommunityact@gmail.com)")
                    }
                    Button(
                        onClick = {
                            showDialog = false
                            viewModel.simulateGoogleSignIn(
                                testEmail = "student@aura.edu",
                                testName = "Aura Student"
                            )
                        },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text("Simulate Student (student@aura.edu)")
                    }
                    TextButton(
                        onClick = { showDialog = false },
                        modifier = Modifier.align(Alignment.End)
                    ) {
                        Text("Cancel")
                    }
                }
            }
        )
    }
}
