#!/bin/bash
awk '
/suspend fun getExamBoards/ {
    print "    // Quizzes"
    print "    suspend fun getQuizzes(className: String = \"\", subject: String = \"\", associatedId: String = \"\"): List<com.example.data.models.Quiz> {"
    print "        return try {"
    print "            val query = client.postgrest[\"quizzes\"].select {"
    print "                if (className.isNotEmpty()) filter { eq(\"className\", className) }"
    print "                if (subject.isNotEmpty()) filter { eq(\"subject\", subject) }"
    print "                if (associatedId.isNotEmpty()) filter { eq(\"associatedId\", associatedId) }"
    print "            }"
    print "            query.decodeList<com.example.data.models.Quiz>().sortedByDescending { it.createdAt }"
    print "        } catch (e: Exception) {"
    print "            e.printStackTrace()"
    print "            emptyList()"
    print "        }"
    print "    }"
    print ""
    print "    suspend fun addQuiz(quiz: com.example.data.models.Quiz): String {"
    print "        return try {"
    print "            val newId = if (quiz.id.isEmpty()) UUID.randomUUID().toString() else quiz.id"
    print "            val newQuiz = quiz.copy(id = newId, createdAt = System.currentTimeMillis())"
    print "            client.postgrest[\"quizzes\"].insert(newQuiz)"
    print "            newId"
    print "        } catch (e: Exception) {"
    print "            e.printStackTrace()"
    print "            \"\""
    print "        }"
    print "    }"
    print ""
    print "    suspend fun deleteQuiz(quizId: String) {"
    print "        if (quizId.isNotEmpty()) {"
    print "            try {"
    print "                client.postgrest[\"quizzes\"].delete { filter { eq(\"id\", quizId) } }"
    print "            } catch (e: Exception) { e.printStackTrace() }"
    print "        }"
    print "    }"
    print ""
    print "    suspend fun getQuizQuestions(quizId: String): List<com.example.data.models.QuizQuestion> {"
    print "        return try {"
    print "            client.postgrest[\"quiz_questions\"].select {"
    print "                filter { eq(\"quizId\", quizId) }"
    print "            }.decodeList<com.example.data.models.QuizQuestion>().sortedBy { it.order }"
    print "        } catch (e: Exception) {"
    print "            e.printStackTrace()"
    print "            emptyList()"
    print "        }"
    print "    }"
    print ""
    print "    suspend fun saveQuizQuestions(quizId: String, questions: List<com.example.data.models.QuizQuestion>) {"
    print "        try {"
    print "            client.postgrest[\"quiz_questions\"].delete { filter { eq(\"quizId\", quizId) } }"
    print "            if (questions.isNotEmpty()) {"
    print "                val newQuestions = questions.map { if (it.id.isEmpty()) it.copy(id = UUID.randomUUID().toString(), quizId = quizId) else it.copy(quizId = quizId) }"
    print "                client.postgrest[\"quiz_questions\"].insert(newQuestions)"
    print "            }"
    print "        } catch (e: Exception) {"
    print "            e.printStackTrace()"
    print "        }"
    print "    }"
    print ""
    print "    suspend fun saveQuizResult(result: com.example.data.models.QuizResult) {"
    print "        try {"
    print "            val newResult = result.copy(id = UUID.randomUUID().toString(), createdAt = System.currentTimeMillis())"
    print "            client.postgrest[\"quiz_results\"].insert(newResult)"
    print "        } catch (e: Exception) {"
    print "            e.printStackTrace()"
    print "        }"
    print "    }"
    print ""
    print "    suspend fun getQuizResultsByUser(userId: String): List<com.example.data.models.QuizResult> {"
    print "        return try {"
    print "            client.postgrest[\"quiz_results\"].select {"
    print "                filter { eq(\"userId\", userId) }"
    print "            }.decodeList<com.example.data.models.QuizResult>().sortedByDescending { it.createdAt }"
    print "        } catch (e: Exception) {"
    print "            e.printStackTrace()"
    print "            emptyList()"
    print "        }"
    print "    }"
    print ""
}
{ print }
' app/src/main/java/com/example/data/repository/AuraRepository.kt > temp.kt && mv temp.kt app/src/main/java/com/example/data/repository/AuraRepository.kt
